---
title: "SwiftPredict. EDA v2"
author: "Dmitry Dolgov"
date: "12/3/2020"
output: html_document
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
```

# Plot word coverage

```{r word_coverage}
words <- ngrams[[1]]
words$perc <- words$frequency / sum(words$frequency)
words$cumperc <- cumsum(words$perc)
cover <- vector(mode = 'integer')
cover["50"] <- min(which(words$cumperc>=.5))
cover["90"] <- min(which(words$cumperc>=.9))
cover["95"] <- min(which(words$cumperc>=.95))
cover["99"] <- min(which(words$cumperc>=.99))
```

```{r plotPercentageCovered}
ggplot(data=words, aes(x=as.integer(rownames(words)), y=cumperc)) + geom_point(color='steelblue') + 
        scale_x_continuous(labels = comma, trans="log10", breaks=c(10, cover["50"], 1000, cover["90"], cover["95"], cover["99"]), minor_breaks = NULL) +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
        labs(x='Words count', y='Cumulative % covered') +
        geom_hline(yintercept=.5) + 
        geom_hline(yintercept=.9) + 
        geom_hline(yintercept=.95) +
        geom_hline(yintercept=.99)
```

# Choose dictionary and plot top words

```{r dict}
dict_size <- 50000
dict_cover <- words[dict_size,]$cumperc

ggplot(data=words[1:30,], aes(x=reorder(feature, -perc), y=perc)) + geom_bar(stat='identity') + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab('word')
```
